apiVersion: apps/v1
kind: Deployment
metadata:
  name: solidarity-connection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solidarity-connection
  template:
    metadata:
      labels:
        app: solidarity-connection
    spec:
      containers:
        - name: solidarity-connection
          image: solidarityconnectionacr.azurecr.io/solidarity-connection:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 600Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: DONATION_PROCESSED_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: DONATION_PROCESSED_TOPIC
            - name: DONATION_PROCESSED_SUBSCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: DONATION_PROCESSED_SUBSCRIPTION
            - name: NewRelic__OtlpEndpoint
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: NewRelic__OtlpEndpoint
            - name: NewRelic__Protocol
              valueFrom:
                configMapKeyRef:
                  name: users-api-config
                  key: NewRelic__Protocol
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: fiap-users-secret
                  key: ConnectionStrings__DefaultConnection
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: fiap-shared-secret
                  key: ServiceBus__ConnectionString
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: fiap-shared-secret
                  key: NEW_RELIC_LICENSE_KEY
            - name: JwtSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: fiap-users-secret
                  key: JwtSettings__SecretKey
            - name: JwtSettings__Issuer
              valueFrom:
                secretKeyRef:
                  name: fiap-users-secret
                  key: JwtSettings__Issuer
            - name: JwtSettings__Audience
              valueFrom:
                secretKeyRef:
                  name: fiap-users-secret
                  key: JwtSettings__Audience

