apiVersion: v1
kind: Service
metadata:
  name: solidarity-connection
  labels:
    app: solidarity-connection
spec:
  type: LoadBalancer
  selector:
    app: solidarity-connection
  ports:
    - name: http
      port: 8083
      targetPort: 80
