apiVersion: v1
kind: Secret
metadata:
  name: fiap-shared-secret
  namespace: solidarity-connection
type: Opaque
stringData:
  ServiceBus__ConnectionString: "<secret>"
  NEW_RELIC_LICENSE_KEY: "<secret>"