apiVersion: v1
kind: Secret
metadata:
  name: fiap-users-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "<serect>"
  JwtSettings__SecretKey: "<serect>"
  JwtSettings__Issuer: "<serect>"
  JwtSettings__Audience: "<serect>"

